image: Ubuntu

stack: jdk 11

branches:
  only:
    - main
    - selendine

build: off

install:

  - java -jar ./artifacts/app-order.jar &
  - chmod +x gradlew

build_script:
  - ./gradlew test --info -Dselenide.headless=true